### ISSUE TITLE
Cargo una nueva campaña y no me la muestra en mi panel de usuario

### ISSUE THREAD

**Issue by jforni** [LeoDm123/EmailMkt-Front#1]
Cargo una nueva campaña y no me la muestra en mi panel de usuario, y con el usuario Admin la activo. 
![image](https://github.com/LeoDm123/EmailMkt-Front/assets/6042663/b1a61455-6b9c-4a2a-842e-5ea91c3704ba)
![image](https://github.com/LeoDm123/EmailMkt-Front/assets/6042663/92b2befc-8c6e-49c6-899e-780a3992530b)

**Comment by LeoDm123** [comment]
Que raro, acabo de probar en crear una campaña con mi perfil y luego verla con mi perfil y al parecer todo funcionar bien.  Por alguna razón, creó la campaña con el mail de admin.  ¡Saludos cordiales!  Ing. Leandro José Diaz Meiners.  De: Julio ForniEnviado: lunes, 22 de abril de 2024 16:38Para: LeoDm123/EmailMkt-FrontCC: SubscribedAsunto: [LeoDm123/EmailMkt-Front] Cargo una nueva campaña y no me la muestra en mi panel de usuario (Issue #1) Cargo una nueva campaña y no me la muestra en mi panel de usuario, y con el usuario Admin la activo.image.png (view on web)imagepng (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> Libre de virus.www.avast.com
